name: Terraform Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_538 }}    
          
      - name: Switch to Kubernetes folder
        run: cd ApoTestingCP/KubernetesCluster  # Change to your KubernetesCluster folder path 

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform fmt
        run: terraform validate

      - name: Terraform validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      
