name: kubernetes-cluster-plan
run-name: ${{ github.actor }} is running for see the Kubernetes cluster plan before execution on Azure

on:
  workflow_call:
    inputs:
      kubernetestffilesfolder:
        description: 'Kubernetes folder which is having all tf files'
        required: true
        type: string
   

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.kubernetestffilesfolder }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Switch to KubernetesCluster folder
        run: echo "Switching to ${{ inputs.kubernetestffilesfolder }} folder"  
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NAVEEN538_AZURE_CREDENTIALS }}   
                   
        
      - name: Copy tfstate file to kubernetestffilesfolder
        run: |
          cp tfstatefiles/terraform.tfstate .
          
      - name: List all files under kubernetestffilesfolder
        run: ls -lrt   

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform fmt
        run: terraform validate

      - name: Terraform validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan 
        
     

      
